ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS refund_status TEXT NOT NULL DEFAULT 'none',
  ADD COLUMN IF NOT EXISTS refund_reason TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS refunded_at   TIMESTAMPTZ;
