ALTER TABLE categories
  ADD COLUMN IF NOT EXISTS description TEXT    NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS sort_order  INT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_active   BOOLEAN NOT NULL DEFAULT true;
