run:
  timeout: 5m

linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - gofmt
    - misspell
  disable:
    - errcheck
    - goimports
    - gocritic
    - gosec
    - bodyclose
    - contextcheck
    - sqlclosecheck

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters: [govet, staticcheck]
    - path: "vendor/"
      linters: [all]
